[project]
name = "advent-of-code"
version = "0.1.0"
description = "Solving Advent of Code puzzles"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.15.1",
]

[tool.basedpyright]
typeCheckingMode = "off"
ignore = ["*"]
